ingress:
  - className: nginx
    name: default-application
    host: test.htquanq
    paths:
      - path: /
        serviceName: default-app
        servicePort: 8080
      - path: /abc
        serviceName: second-app
        servicePort: http
  - name: second
    host: abc.htquanq
    paths:
      - path: /
        serviceName: test
        servicePort: 9090
      - path: /xyz
        serviceName: another-test
        servicePort: https

testContainers:
  - name: test
    image: nginx
    ports:
      - containerPort: 80
        name: http
        protocol: tcp
    limits:
      memory: 100Mib
      cpu: 2
    command:
      - nginx -t
    args:
      - /etc/nginx/ngin.conf
  - name: test2
    image: nginx2
    ports:
      - containerPort: 8080
        name: application
        protocol: tcp
    limits:
      memory: 200Mib
      cpu: 3
    env:
      - HTQUANQ: 123